version: '3.6'

services:
  authserver:
    build:
      context: ./services-python/authserver
    networks:
      - authserver
    environment:
      SECRET_KEY: ''
      TOKEN_KEY: ''
      CLIENT_ID: ''
      CLIENT_SECRET: ''
      POSTGRESQL_HOST: ''
      POSTGRESQL_PORT: ''
      REDIS_HOST: ''
      REDIS_PORT: ''

networks:
  authserver:
    external:
      name: gateway
