http:
  port: 8080

apiEndpoints:
  authentication:
    host: '*'
    paths: /token/*
    methods: ["POST","OPTIONS"]

serviceEndpoints:
  authentication:
    url: '${AUTHENTICATION_SERVICE_URI}/o'

policies:
  - cors
  - log
  - oauth2
  - proxy
  - jwt

pipelines:
  authentication:
    apiEndpoints:
      - authentication
    policies:
      - proxy:
          - action:
              serviceEndpoint: authentication
              changeOrigin: true

  # user:
  #   apiEndpoints:
  #     - user
  #   policies:
  #     - jwt:
  #       - action:
  #           secretOrPublicKey: '${SECRET_KEY:-SECRET_KEY}'
  #           checkCredentialExistence: false
  #     - proxy:
  #         - action:
  #             serviceEndpoint: books
  #             changeOrigin: true
