http:
  port: 8080

apiEndpoints:
  authentication:
    host: '*'
    paths: /user-login/*
    methods: ["POST","OPTIONS"]

  userlist:
    host: '*'
    paths: /user-list/*
    methods: ["GET","OPTIONS"]

serviceEndpoints:
  authentication:
    url: '${AUTHENTICATION_SERVICE_URI}/auth/'

  userlist:
    url: '${AUTHENTICATION_SERVICE_URI}/api/'

policies:
  - cors
  - log
  - oauth2
  - proxy
  - jwt

pipelines:
  authentication:
    apiEndpoints:
      - authentication
    policies:
      - proxy:
          - action:
              serviceEndpoint: authentication
              changeOrigin: true

  userlist:
    apiEndpoints:
      - userlist
    policies:
      - jwt:
        - action:
            secretOrPublicKey: '${SECRET_KEY:-SECRET_KEY}'
            checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: userlist
              changeOrigin: true
